name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/.cache/ms-playwright

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Cache Playwright Dependencies
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.cache/ms-playwright
          key: ${{ runner.os }}-playwright

      - name: Install Playwright Dependencies
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium --with-deps

      - name: Test
        run: pnpm run test
